flags: {}

resolver: lts-6.6
# compiler: ghcjs-0.2.0.900006006_ghc-7.10.3

compiler-check: match-exact

setup-info:
  ghcjs:
    source:
      ghcjs-0.2.0.900006006_ghc-7.10.3:
         url: "https://tolysz.org/ghcjs/lts-6.6-900006006.tar.gz"

allow-newer: true

packages:
- location: '.'
- location:
    git: https://github.com/ryantrinkle/reflex.git
    commit: 2e9a8de650857424fb93b372c6d00fda5e99d380
# 3a7fb30dde160bc31c0bba4f42f7666ea6ca054a
  extra-dep: true
- location:
    git: https://github.com/ryantrinkle/reflex-dom.git
    commit: 77e0c270f6270561d70d0b6ad925fb1ea82612a8
# 5318d581fe3ef7b2b0f70ac352d6c56700124b98
  extra-dep: true
- location:
     git: https://github.com/isomorphism/these.git
     commit: cf68c46bd049d23938f351da5618e9a09ef1102c

extra-deps:
- ref-tf-0.4
- these-0.6.1.0
- ghcjs-dom-0.2.4.0
- zenc-0.1.1
